---
# for kube-apiserver
etcd_servers: http://192.168.1.201:4001
apiserver_insecure_port: 1100
apiserver_service_cluster_ip_range: 20.1.0.0/16

# for kube-controller-manager, kube-scheduler
master_url: http://192.168.1.201:1100

ca_crt_CN: ecip.hp.com
server_key_CN: 192.168.1.201
