---
# for kubelet, kube-proxy
kube_master_url: http://192.168.18.133:8080
docker_runtime_root_dir: /var/lib/docker
install_quagga_router: true
# quagga router docker image info
quagga_router_image_id: f96cfe685533
quagga_router_image_tag: index.alauda.cn/georce/router
 